---
title: "Differential Expression Analysis"
output: html_document
date: "2026-05-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load required packages

```{r message=FALSE, warning=FALSE}
library(DESeq2) 

library(tidyverse)
library(gplots)

```
## Load the data

```{r}
#get counts data
counts <- read.delim("gene_counts.tsv", row.names=1)
#get the sample metadata
sample_info <- read.delim("sample_metadata.tsv", row.names=1)


#make sure all the rownames match
all(colnames(counts) %in% rownames(sample_info))
#make sure that they are in the correct order
all(colnames(counts) == rownames(sample_info))
sample_info <- sample_info[colnames(counts), , drop=FALSE] #reorder the colnames
all(colnames(counts) == rownames(sample_info))

head(counts)
head(sample_info)


```
## Run DEseq
```{r}
#create a DESeq object
dds <- DESeqDataSetFromMatrix(countData = counts,
                       colData = sample_info,
                       design = ~ condition)

dds

#remove rows with low gene counts
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]

dds

#set the factor level
dds$condition <- relevel(dds$condition, ref = "normal")

#run DESeq
dds <- DESeq(dds)
res <- results(dds)

```
## Explore the results
```{r}
#order by adjusted p-value
res <- res[order(res$padj), ]
summary(res)

#get information about testing used
mcols(res)$description

#save the data
resdata <- merge(as.data.frame(res),
as.data.frame(counts(dds, normalized=TRUE)),
by="row.names", sort=FALSE)
names(resdata)[1] <- "Gene"
head(resdata)
write.table(resdata, file="de_default.txt",
sep="\t", quote=F)

#1% false discovery rate
res0.01 <- results(dds, alpha = 0.01)

res0.01 <- res0.01[order(res0.01$padj), ]
summary(res0.01)

#save the data
res0.01data <- merge(as.data.frame(res0.01),
as.data.frame(counts(dds, normalized=TRUE)),
by="row.names", sort=FALSE)
names(res0.01data)[1] <- "Gene"
head(res0.01data)
write.table(res0.01data, file="de_01.txt",
sep="\t", quote=F)

resultsNames(dds) #check the contrast
#plotMA
png("DE_MA.png", width=800, height=600, res=300)
plotMA(res)
dev.off()
plotMA(res)

#Top five most upregulated gene
res_df <- as.data.frame(res0.01)
n <- nrow(res_df)
n

#get the top 10 upregulated

top10_up <- res_df %>%
  filter(padj < 0.01) %>%
  arrange(desc(log2FoldChange)) %>%
  head(10)

top10_up

#top10 most downreg
top10_down <- res_df %>% 
  filter(padj <0.01) %>%
  arrange(log2FoldChange) %>%
  head(10)

top10_down

#combine into one table
top10_combined <- rbind(top10_up, top10_down)
top10_combined

#save the de genes
top10_combined$gene_id <- rownames(top10_combined)

write.table(top10_combined,
            file="top10_DEGs.tsv",
            sep="\t",
            quote=FALSE,
            row.names=FALSE)
res_df$gene_id <- rownames(res_df)

all_de <- res_df %>%
  na.omit() %>%
  filter(padj < 0.01) %>%
  arrange(gene_id)

all_de


write.table(all_de,
            file="all_DEGs.tsv",
            sep="\t",
            quote=FALSE,
            row.names=FALSE)
```

## Explore genes of interest
```{r}
#plot counts of the most upregulated gene
png("most_upreg.png", width=1800, height=1400, res=300)
plotCounts(dds, gene="GENE_0669", intgroup="condition")
dev.off()
plotCounts(dds, gene="GENE_0669", intgroup="condition")
#plot the counts of the most downregulated gene
png("most_downreg.png", width=1800, height=1400, res=300)
plotCounts(dds, gene="GENE_0851", intgroup="condition")
dev.off()
plotCounts(dds, gene="GENE_0851", intgroup="condition")

```

## Examine distribution

```{r}
#plot p-value distribution
png("res_pvaldis.png", width=1800, height=1400, res=300)
hist(res$padj, breaks=50, col="green")
dev.off()
hist(res$padj, breaks=50, col="green")

#plot log2 fold change distibution
png("res_logdis.png", width=1800, height=1400, res=300)
hist(res$log2FoldChange, breaks=50, col="green")
dev.off()
hist(res$log2FoldChange, breaks=50, col="green")

```

## Heatmap

```{r}
#log transform
ltdds <- rlogTransformation(dds)
#plot histogram of logtransformed
hist(assay(ltdds))

#plot heatmap
png("heatmap.png", width=2000, height=2000, res=300)
sampleDists <- as.matrix(dist(t(assay(ltdds))))
heatmap.2(as.matrix(sampleDists), key=F, trace="none",
col=colorpanel(100, "darkblue", "lightgreen"), margin=c(10, 10))
dev.off()

sampleDists <- as.matrix(dist(t(assay(ltdds))))
heatmap.2(as.matrix(sampleDists), key=F, trace="none",
col=colorpanel(100, "darkblue", "lightgreen"))


```

## PCA
```{r}
png("pca.png", width=1800, height=1400, res=300)
plotPCA(ltdds, intgroup=c("condition"))
dev.off()
plotPCA(ltdds, intgroup=c("condition"))
```



